version: 2

sphinx:
  configuration: ./conf.py

# Explicitly set the version of Python and its requirements
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
# install:
#   - requirements: docs/requirements.txt
